######################################################################
# Automatically generated by qmake (3.1) Thu Feb 9 13:00:44 2017
######################################################################

TEMPLATE = lib
TARGET = usbnotifier
INCLUDEPATH += include

QT += core

# Input
HEADERS += \
           src/usbdevice.h \
           src/usbdevice_p.h \
           src/usbnotifier.h \
           src/usbnotifier_p.h
SOURCES += \
           src/usbdevice.cpp \
           src/usbnotifier.cpp
